# Generated by Django 2.0.5 on 2018-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='quality_of_work',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
    ]
