# Generated by Django 2.0.5 on 2018-06-08 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180602_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='average_folder_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_main_get_request',
            field=models.TimeField(default=datetime.datetime(1980, 1, 1, 0, 0)),
        ),
    ]
