# Generated by Django 2.0.5 on 2018-06-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180608_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_of_checked_folders',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
