# Generated by Django 2.0.5 on 2018-05-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('is_classified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
            },
        ),
        migrations.CreateModel(
            name='DirectoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('dir_id', models.IntegerField()),
                ('is_bad', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Directory Item',
                'verbose_name_plural': 'Directory Items',
            },
        ),
        migrations.CreateModel(
            name='RootDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Root Directory',
                'verbose_name_plural': 'Root Directories',
            },
        ),
    ]
