# Generated by Django 2.0.5 on 2018-05-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('classifications_amount', models.PositiveIntegerField(default=0)),
                ('directory_class', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Directory',
                'verbose_name_plural': 'Directories',
            },
        ),
        migrations.CreateModel(
            name='DirectoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_bad', models.BooleanField()),
                ('thumbnail_100x100', models.ImageField(default=None, upload_to='')),
                ('thumbnail_200x200', models.ImageField(default=None, upload_to='')),
                ('dir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.Directory')),
            ],
            options={
                'verbose_name': 'Directory Item',
                'verbose_name_plural': 'Directory Items',
            },
        ),
        migrations.CreateModel(
            name='RootDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name': 'Root Directory',
                'verbose_name_plural': 'Root Directories',
            },
        ),
        migrations.AddField(
            model_name='directory',
            name='root_dir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.RootDirectory'),
        ),
    ]
