# Generated by Django 2.0.5 on 2018-05-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('path', 'root_dir')},
        ),
    ]
