# Generated by Django 2.0.5 on 2018-06-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_class', models.TextField(default='')),
                ('bad_photos', models.CharField(default='', max_length=1024)),
            ],
            options={
                'verbose_name': 'Productivity record',
                'verbose_name_plural': 'Productivity table',
            },
        ),
        migrations.AddField(
            model_name='rootdirectory',
            name='dir_full',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('path', 'root_dir')},
        ),
        migrations.AddField(
            model_name='statisticdirectory',
            name='dir',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.Directory'),
        ),
    ]
