# Generated by Django 2.0.5 on 2018-05-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20180530_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory_class', models.TextField(default='')),
                ('bad_photos', models.CharField(default='', max_length=1024)),
                ('dir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.Directory')),
            ],
            options={
                'verbose_name': 'Productivity record',
                'verbose_name_plural': 'Productivity table',
            },
        ),
    ]
