# Generated by Django 2.0.5 on 2018-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20180602_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticdirectory',
            old_name='bad_photos',
            new_name='bad_photos_one',
        ),
        migrations.RenameField(
            model_name='statisticdirectory',
            old_name='directory_class',
            new_name='directory_class_one',
        ),
        migrations.AddField(
            model_name='statisticdirectory',
            name='bad_photos_two',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='statisticdirectory',
            name='directory_class_two',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='statisticdirectory',
            name='user_id_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statisticdirectory',
            name='user_id_two',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='directoryitem',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
