# Generated by Django 2.0.5 on 2018-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20180603_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticdirectory',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
